### ISSUE TITLE
How to evaluate the quality of an algorithm？

### ISSUE THREAD

**Issue by Xiaoling-Zhang** [thieu1995/mealpy#1]
There are a lot of algorithms here, and you also gave them an evaluation(such as BEST,best,strong), but what do you use to judge the qualities of these algorithm? Through convergence time or accuracy？Besides，sometimes we have a very large parameter space, do these algorithms have dimensional restrictions? Can they find a good solution?

**Comment by thieunguyen5991** [comment]
I classify algorithms based on convergence and accuracy. I haven't evaluated all algorithms for all types of functions yet, the judge is my personal subjective based on the performance of the algorithm on the issues that I am doing.

For large searching space, the algorithm is good or not depends on your problem. For example:
+ If your evaluation function is uni-modal or multi-modal, then the algorithm which includes the levy-flight technique will most likely find a good solution even if the n-dimension is 1000.
+ If your evaluation function is very complex, such as composition or hybrid functions, it will work well if n-dimension < 100 or 200.

- You can check the CEC competitions to know more good algorithms that can solve with large-dimension. (https://dblp.org/db/conf/cec/index)

**Comment by Xiaoling-Zhang** [comment]
Thanks a lot! Do you have the convergence comparison curve of different algorithms on your personal subjective? And I saw you marked ApaSA as the BEST algorithm, I looked at the implementation, but I feel that formulas 3 and 5 are not exactly the same as the original text?

**Comment by thieunguyen5991** [comment]
I didn't save any of the convergence comparison curves. You can easy to create one. When runs the algorithm, choose the parameter "log = True", you will get the convergence results printed out. 

Before you check any algorithms. You should read two things:

+ Version: Changed or Original in comparison table in my GitHub repository.
	==> I marked SpaSA is changed version (Not the original one, reason? --> Below)
+ The comment section at the top of the coding file. I explain why I changed it.

Noted: Most of the algorithm which is changed version meaning:

+ The original paper doesn't show how exactly the equation looks like or they don't explain parameters in equations. 
So I can't implement it based on the paper, I will use my experiment to implement it. Sometimes I change equations, sometimes I change the whole flow of algorithms.
	
+ The paper is some sort of fake, fake equations or fake algorithm and I'm sure the results are fake too. 
You should check my developed version of this library. I reveal some fake papers and algorithms. 
https://github.com/thieunguyen5991/metaheuristics
	

SpaSA is the most recent one (2020). I am not sure about your second question. My implementation of equation 3 and 5 are the one in the paper. 
Only the equation 4 is different because they didn't say anything about matrices A and L. I just use the normal distribution instead.

**Comment by kushal-93** [comment]
How do I set different lower and upper bounds of different parameters when they are using one custom objective function? I need 7 parameters optimized for one objective function.
