### ISSUE TITLE
can set parameters to int?

### ISSUE THREAD

**Issue by kiennt111** [thieu1995/mealpy#10]
Hi, how to set parameters when performing an optimization algorithm that takes only integer values within a specified range?

**Comment by thieu1995** [comment]
Hi @kiennt111 ,

This library is for continous domain, the solution is a sequence of float number, not for discrete domain. 
Still you can make a solution with integer values by making a round function like this. 

```
from numpy import round, array, int32, uniform

def round_down_solution(solution:array):
     temp = solution.astype(int32)
     return temp

def round_simple_solution(solution:array):
      temp = round(solution).astype(int32)
      return temp
```

# Note: different between round_down and round_simple

```
solution = np.array([2.3, 4.5, 4.50, 4.6, 0.8, 1.0])
t1 = round_down_solution(solution)
===> t1 = array([2, 4, 4, 4, 0, 1])

t2 = round_simple_solution(solution)
===> t2 = array([2, 4, 4, 5, 1, 1])
```

If you want a unique integer value in a solution, that's not possible with this library. Of course, you can still do it, but eventually, you have to change all the function in the root.py file and all the function in all algorithms. Meaning you are writing your own library instead of using my library.

**Comment by kiennt111** [comment]
Thank you very much for the detailed answers and good suggestions .
