### ISSUE TITLE
[BUG]: Original hill climbing algorithm step_size issue

### ISSUE THREAD

**Issue by SkyLin1020** [thieu1995/mealpy#114]
### Description of the bug

the step_size in hill climbing looks confused. when epoch is low, step_size approach -1. while when epoch is high, step size approach 1.

### Steps To Reproduce

step_size = 1 - 2 * (1 - (epoch + 1) / self.epoch)

**Comment by thieu1995** [comment]
Hi @SkyLin1020,

HC is a single-based solution (a local search algorithm). It was originally not intended to be included in this library, which primarily focuses on population-based solutions (global search algorithms). However, many people have asked me to implement it, so I had to adapt this algorithm to fit within this library.

The 'pop_size' parameter does not matter for this algorithm. That's why you can see this line of code: 
https://github.com/thieu1995/mealpy/blob/master/mealpy/math_based/HC.py#L76
Here, I consider 'self.g_best' as the searching solution for this algorithm.

Additionally, there is no 'step_size' variable in the original algorithm. I introduced this variable to improve the algorithm's results. It's possible that this 'step_size' doesn't provide significant advantages, but if you look at the original HC algorithm in the paper, there is no stored information about the evolution process; it is essentially a random process.

Considering these modifications, I believe it would be more appropriate to rename the class as 'DevHC' to indicate that it's a modified or developed version of the original HC algorithm.

**Comment by SkyLin1020** [comment]
Hi @thieu1995 ,
thank you for your reply. I will try swarmHC to solve my problem.
but considering the step_size in OriginalHC, I think it is not reasonable and improved. the step_size goes from -1 to 0 to 1. that means the step_size goes down and then up because the absolute value of step_size matters. with the step_size setting, maybe it can randomly search the space, but it is not a climbing process.,for a climbing process, the step_size may be monotone decreasing like the setting in swarmHC.
Hope this can help. and if I misunderstanding the algorithm, hope you can point it out.

**Comment by SkyLin1020** [comment]
> Hi @SkyLin1020,
> 
> HC is a single-based solution (a local search algorithm). It was originally not intended to be included in this library, which primarily focuses on population-based solutions (global search algorithms). However, many people have asked me to implement it, so I had to adapt this algorithm to fit within this library.
> 
> The 'pop_size' parameter does not matter for this algorithm. That's why you can see this line of code: https://github.com/thieu1995/mealpy/blob/master/mealpy/math_based/HC.py#L76 Here, I consider 'self.g_best' as the searching solution for this algorithm.
> 
> Additionally, there is no 'step_size' variable in the original algorithm. I introduced this variable to improve the algorithm's results. It's possible that this 'step_size' doesn't provide significant advantages, but if you look at the original HC algorithm in the paper, there is no stored information about the evolution process; it is essentially a random process.
> 
> Considering these modifications, I believe it would be more appropriate to rename the class as 'DevHC' to indicate that it's a modified or developed version of the original HC algorithm.

Hi @thieu1995 ,
thank you for your reply. I will try swarmHC to solve my problem.
but considering the step_size in OriginalHC, I think it is not reasonable and improved. the step_size goes from -1 to 0 to 1. that means the step_size goes down and then up because the absolute value of step_size matters. with the step_size setting, maybe it can randomly search the space, but it is not a climbing process.,for a climbing process, the step_size may be monotone decreasing like the setting in swarmHC.
Hope this can help. and if I misunderstanding the algorithm, hope you can point it out.

**Comment by thieu1995** [comment]
Hi @SkyLin1020 ,

Sorry for the late reply. Yes, you are right. 

Initially, I thought climbing meant moving from the bottom up, which is why I set the step_size value from (-1 to 0 to 1). 
But in reality, it should be able to go both down and up randomly. 
Setting the step_size as in swarmHC is commonly used in other algorithms. You should consider using swarmHC instead.

**Comment by thieu1995** [comment]
@SkyLin1020 , 
If there is nothing here I will close this issue now. Feel free to open if needed.
