### ISSUE TITLE
Development of new hybrid nature inspired algorithm

### ISSUE THREAD

**Issue by ashugowda** [thieu1995/mealpy#12]
Hello Sir,
This is Ashwini M
B.E Computer Science student 
Karnataka
India

I am a final year student,for our final year major project we are facing issue in the implementation of hybrid nature inspired algorithm n testing them on cec benchmark functions.

I just now saw your GitHub repository n got to know that you have great knowledge in nature inspired algorithms n cec functions.

I request you to please help us in our project implementation sir,it will be really helpful for us.And we are three of us in our team,so we will be able to pay you around 15,000 INR.

I will attach base paper n requirements for your reference.

Requirements:
1. Development of new hybrid nature inspired algorithm with ABC as base algorithm.
2.Testing the new hybrid algorithm on 2014 CEC benchmark functions along with other existing algorithms
3. Performance analysis of hybrid algorithm with respect to existing algorithms on cec benchmark functions using Wilcoxon Rank test.
4. Performance analysis of hybrid algorithm with respect to existing algorithm on cec benchmark functions using convergence graphs

Please please kindly reply back and provide acknowledgment sir.

Thank you....

With Regards,
Ashwini M

[14_chapter6.pdf](https://github.com/thieu1995/mealpy/files/6415066/14_chapter6.pdf)

**Comment by thieu1995** [comment]
Hi @ashugowda ,

Usually, I help other researchers without money when I was studied at university. But now I have a full-time job so I don't have much time to do the task.

If this is your major project in the final year. I seriously ask you to study on your own. 
If you think this project is too big for you, you can't finish it this semester. 
Then spend one more semester to finish it. 

It is just the first challenge you have to pass. There are lots of obstacles you have to overcome out there. Just don't give up, you will be just fine.

Here are my pieces of advice on your problem.

1. Try to implement your own ABC algorithm, or read my ABC code in this library. Understand it.
2. Choice an algorithm marked with "easy" in the "Difficulty" column of the table in README.md file.
I marked "easy" because it will be easy to read that algorithm, so you can easy to learn it on your own. 
3. Try to mix some equations in both algorithms you have implemented above.
4. Read and try to implement the CEC function or you can just use my library "https://github.com/thieu1995/opfunu"
5. Read the paper about the Wilcoxon Rank test.
6. Try to use some other algorithms in this library.
7. Test all of them with the CEC function using convergence graphs.
