### ISSUE TITLE
get the epoch number in the main function

### ISSUE THREAD

**Issue by Med-Rokaimi** [thieu1995/mealpy#125]
Hey, thank you again for this great work.
Sometimes the algorithm running will be stopped for one reason or other. I would like to get the current epoch when it stopped.
for example in my fitness function in the main file:

def fitness_function(solution, data):
    structure = decode_solution(solution, data)
    fitness = generate_loss_value(structure, data)
   #print(current_eopch)
    return fitness

I know you are priniting the info from the logger but I couldn't reach the current epoch value from my main.py 

Thank you again and agian

**Comment by thieu1995** [comment]
Hi @Med-Rokaimi ,

Currently, there is no variable to store current epoch value. I just calculate it and passing through the function in the solving process. Why? because I feel like it doesn't important to store that value. 

If you still want that value. This code may help you get it. 
`print(len(model.history.list_global_best))`

Also, the above code is from previous version of mealpy. You should use the latest version 3.0.1

**Comment by Med-Rokaimi** [comment]
Thank you for your reply. 
You mean my code in the question belongs to an old version?

**Comment by thieu1995** [comment]
@Med-Rokaimi,

I think so. Because in the new version it should be objective_function.

**Comment by Med-Rokaimi** [comment]
Yes it is. I'm using 2.4 version. I will move to the last one.
Thank you
