### ISSUE TITLE
[BUG]: Minor differences on OOA, MPA and WarSo

### ISSUE THREAD

**Issue by migcaslas** [thieu1995/mealpy#129]
### Description of the bug

First, thank you for creating and maintaining this comprehensive repository of metaheuristic algorithms. It has been of great help to me, and I hope to publish on this subject soon, including of course the corresponding citation.

 I have worked with different algorithms, and I believe there might be slight differences in three of them compared to the original articles:

- **MPA**: On line 81
`t = self.epoch`
If I understand the code correctly, self.epoch contains the maximum number of generations, not the current one. If so, the algorithm always chooses the exploitation phase and does not go through the previous two. I think it should be:
`t = epoch`

- **OOA**: I have noticed a discrepancy between the paper describing the algorithm and the associated Matlab code. According to the paper, the selection of the best solutions during exploration (position identification and hunting the fish) is performed on the population of the previous generation and it is not updated considering the solutions of the current one. This would affect the `idxs` obtained on line 78 and, in addition, would make the algorithm parallelizable, since the evolution of each solution would be independent.

- **WarSO**: I believe that by sorting the solutions on line 72 (`get_sorted_population`), the applied weights (`wl`) do not correspond to the respective agent (soldier) on lines 77 and 80. On the other hand, I think the algorithm can also be parallelizable, as the solutions are not dependent on the rest of their generation in the original algorithm.

I have the corresponding changes in my local version. If you think it's appropriate, I can make a pull request for you to evaluate them, and if they are suitable, I will make the commit.

Thanks again!

### Steps To Reproduce

.

**Comment by thieu1995** [comment]
@migcaslas,

Thanks for using our library. Our concerned about bugs have been fixed in recent commits.

1. MPA has been fixed.
2. OOA. I'm not sure what you mean, but this algorithm cannot be parallelized. If you look at line 85, you'll see that the permutation operation makes it impossible to parallelize the algorithm. Additionally, we have already warned users about this limitation. Therefore, even if it were possible to parallelize the algorithm using your suggested approach, we would not do it because it would make it difficult for users to compare our code with the original paper.
3. WarSO. In the latest version, we have converted all agent properties to be attached to the agent itself. As a result, when we sort the population, the properties are sorted along with the agent. However, it seems that we missed this one. Nevertheless, this issue has been addressed and fixed in the latest commit. Besides, this algorithm can't be parallelized with line 75. We use permutation operater.

**Comment by migcaslas** [comment]
@thieu1995,

Apologies for the delayed response and for not realizing that I was using an earlier version of the library. 

I believe that in the case of OOA, it could be parallelized by permuting the population from the previous epoch (before the for iteration) without updating the agents's solutions during the execution of the new one. Additionally, it seems to me that this approach is more in line with what is described in the original article. The same applies to WarSo. However, as you mentioned, this would impact users of the library who have already conducted tests with these algorithms. 

Thanks for your response! I close this thread.
