### ISSUE TITLE
[FEAT]: i think it is better to add introduction to some specified parameters like name="delta"

### ISSUE THREAD

**Issue by Code-Newborn** [thieu1995/mealpy#156]
### Description

what is name = "delta"  means in following pic? thank you for explanation.
![image](https://github.com/thieu1995/mealpy/assets/47051839/bbf8a8f2-0c81-4943-b4f7-983bc9cdaa6a)

**Comment by thieu1995** [comment]
@Code-Newborn ,

**It is just a name for your decision variables**. Since this is FloatVar, you don't have to call the decode_function(). So you don't need to set the name for it. However, other classes like IntegerVar, BoolVar,... you need to set the name for it. So when you use decode_function(), you can get the original value based on these names.

**Comment by Code-Newborn** [comment]
@thieu1995,
Thank you for you timely reply☺️. It means that this property is optional. it is for set the variable name of  bounds and I don't need to config it. Is it ?

**Comment by thieu1995** [comment]
@Code-Newborn,

Yes, you don't need to set it if the decisions variables you are using is FloatVar. But for other variables like IntegerVar, BoolVar... you have to set a name for it. It is just a name, you can name it as anything you want. For FloatVar, you don't need to set it.

**Comment by Code-Newborn** [comment]
Thank you! MEALPY is really a great Python module😁
