### ISSUE TITLE
[BUG]: The Mealpy library exhibits integer boundary and time termination condition errors.

### ISSUE THREAD

**Issue by Bardbo** [thieu1995/mealpy#158]
### Description of the bug

In line 207 of space.py, the recommended method for boundary repair for integer decision variable types employs the \verb|np.clip| function, which may result in inaccurate values for integer decision variables. Therefore, it is recommended to refer to the following changes:

```python
	class FixedIntegerVar(mealpy.IntegerVar):
        def correct(self, x)
            x = np.clip(x, self.lb, self.ub)
            x = self.round(x)
            return np.array(x, dtype=int)
```

An error in the timing of the optimizer.py program has been identified on line 197. One possible solution to the aforementioned issue is to modify the code in the following manner:
```python
# original code 
finished = self.termination.should_terminate(epoch, 
self.nfe_counter, time.perf_counter(), es)
# modified code
finished = self.termination.should_terminate(epoch, 
self.nfe_counter, time.perf_counter() - \
self.termination.start_time, es)
```
 This modification ensures that the time calculation is accurate.

### Steps To Reproduce

Please review the **description of the bug** content and forgive me for my poor English

**Comment by thieu1995** [comment]
@Bardbo,

You should read more carefully and provide an example to show how the bug is identified.

1. The `correct` function is used to set the bounds for variables. In the `IntegerVar` class, the bounds are defined by `lb` and `ub`. Whenever you need a final solution (which involves integer variables), you need to call the `decode` function.

2. The `should_terminate` function in the termination.py module already takes the start time into account.
