### ISSUE TITLE
Add Hybrid Optimizer

### ISSUE THREAD

**Issue by msidrisi91** [thieu1995/mealpy#19]
After I starting working on some hybrid optimizers, I realised those should be present here too. Can I send a pull request to add the optimizers listed below?

1. Manta-Ray Foraging Optimization (MRFO) + Teaching Learning Optimization (TLO)
2. Brain Storm Optimization (BSO) + Henry Gas Solubility Optimization (HGSO)

**Comment by thieu1995** [comment]
Hi @msidrisi91 

Currently, the purpose of this library is to implement the whole metaheuristic algorithm (the novel / original one first). After that, I will think about the hybrid algorithm and other types of metaheuristics.
There are some hybrid versions for some algorithms in this library because I used them for my research papers.
I still have lots of works to do, the number of the novel algorithm is now more than 300 algorithms and are increasing every week, this library currently contains around 100 algorithms.

If you want to contribute the code, make a pull request. I will check it out.
Best regards,
