### ISSUE TITLE
Report : Error in swam_based SalpSO was found 

### ISSUE THREAD

**Issue by tnilpanapan** [thieu1995/mealpy#39]
Dear, Nguyen Van Thieu 
Firstly, I want to tell you. I really enjoyed watching your 2 hrs. video on Youtube .. it's very impressive and I'm still watching it every day.

Today, I will report the error i've met. and also I cannot fix it by myself.
The Error occurs when I try to use SalpSO opitmizer : from mealpy.swarm_based import SalpSO 

TypeError : unsupported operand type(s) for +: 'NoneType' and 'int'

Best regard
t.nilpanapan    
![SalpSO error NoneType](https://user-images.githubusercontent.com/59508948/147390849-32f6d425-3070-47ac-984a-cf69b24fb2a9.jpg)

**Comment by thieu1995** [comment]
Hi @tnilpanapan ,

I feel like you are using the old version, because in the newest version the class SalpSO is renamed to SSO.
You can install the newest version by:
```
pip uninstall mealpy
pip install mealpy==2.1.2 
```

If you are using the newest version 2.1.2, and pycharm + windows, then try to clear the cache in pycharm by:
File => Invalidate Caches => Choice the first three options => "Invalidate and Restart" button

After that, call the class:
```
from mealpy.swarm_based import SSO 
model = SSO.BaseSSO(...)
```

Best regards,
Thieu

**Comment by tnilpanapan** [comment]
Hi @thieu1995 ,

Wow , the problem is fixed now . Thanks, @thieu1995 
Best regards
