### ISSUE TITLE
Global and cureent best values remain same

### ISSUE THREAD

**Issue by MaameBoamahPoku** [thieu1995/mealpy#42]
Hello @thieu1995 
I have successfully ran GWO-SVM hybrid codes. I saw from the output that the global best and current best remained the same for all the epochs(10, 50,100) that I ran. The same value was returned as the accuracy. What could i be doing wrong please. Secondly which values are the best lb and ub for the objective function? I am asking because you didn't explain that in your video. Thank you for your assistance.
I have attached snips of my codes:
![GWO-SVM-2](https://user-images.githubusercontent.com/91562461/151017663-e017a6e8-824b-4f40-8a1c-5665116d3f7e.JPG)
![GWO_SVM_1](https://user-images.githubusercontent.com/91562461/151017678-d60525a5-bef7-4884-bbea-1e2ab8d0b94e.JPG)

**Comment by thieu1995** [comment]
Hi @MaameBoamahPoku,

It is so obvious that for this problem the maximum accuracy is 0.89744... even after 1 epoch. I hope you understand what you are really doing. You may ask why after only 1 epoch you got the optimal value?
It is because you set population size (pop_size) = 150. Means you've already tried 150 combinations of hyper-parameters (kernel and C). 
You can try the brute-force search with the same value like above. Let's say, C increase from 1 to 1000 with step = 1. And kernel can be like above "rbf", "linear",....
And compare the results you get from brute-force and above MHA method to see the maximum accuracy can get from all combinations is 0.8974... or not. 

I've already explained how to set the lowerbound and upperbound in the video tho. Its depend on the number of values for each hyper-parameter and depend on the type of hyper-parameter.
If hyper-parameter is string, you need to encode function to make it into integer number. And then a decode function to get it back to string value. 
If hyper-parameter is integer, you need to use the function int() like above for kernel. Because the value return from solution is real value. You need int() function to have the integer value.
If hyper-parameter is float, then there is no need to do anything.

**Comment by MaameBoamahPoku** [comment]
Alright, Sir. I will take a critical look at my work and your videos again. Thank you for your response

**Comment by thieu1995** [comment]
Hi @MaameBoamahPoku ,
New version is updated. You can check the GA with multiple options [here.](https://mealpy.readthedocs.io/en/latest/pages/models/mealpy.evolutionary_based.html#module-mealpy.evolutionary_based.GA)
