### ISSUE TITLE
Barycenter method and optimization

### ISSUE THREAD

**Issue by brunolnetto** [thieu1995/mealpy#43]
Hi,

There is a method I work on my master thesis called [Barycenter method](https://arxiv.org/abs/1801.10533). You may find its python implementation [here](https://github.com/brunolnetto/baryopt/tree/master/versions/python). I still do not implemented it on a parallel framework, but it you may find it reasonable to program given the state of the art. I might only compliment for your effort both in implementation and clarification.

Best regards

**Comment by thieu1995** [comment]
Hi @brunolnetto ,
I reviewed the paper and the code you implemented. This method is completely different compare to classical metaheuristics. 
The structure and the flow, especially there is no population-based idea in it. So there is no need to implement using the parallel framework. Because it is faster than general meta-heuristics.

I'm not familiar with the Matlab code. So I can't really understand your MatLab code. But based on the Python version you implemented, there is a mistake or error in your code. You should check that again, I've commented on your repo. 
If you can fix your python version, I may help you to make this algorithm as a population-based method and give it some ideas such as global best, local best, and parallel process. But in the end, it will be a completely new algorithm as compared to the original one (batch or recursive version).

**Comment by brunolnetto** [comment]
Although useful, batch version is not as recommended as recursive one for the parallel metaheuristic version. 

Try to read [this](https://arxiv.org/pdf/1801.10533.pdf), footer p. 9 ~ footer p.10 [(...) "an exploration term using
the barycenter method."]

I suppose you know how to run a jupyter notebook. If not and use linux, try to run my shell script: https://github.com/brunolnetto/engage

:) Live long and prosper.

**Comment by thieu1995** [comment]
@brunolnetto 
Lol, based on your fixed recursive version, I can add the population idea into it and add it to this library. But to really understand your paper, I may need more time, especially lots of math equations there. 
I can read and understand python code faster than math equations. Anyway, I trust you with the implementation of this algorithm. I May review it later to verify it tho.
