### ISSUE TITLE
A problem in Sparrow search algorithm

### ISSUE THREAD

**Issue by jacobkndy** [thieu1995/mealpy#45]
Hi, 
I hope you doing well.
Maybe I find out two problem with mealpy library, so I will share it with u and be thankful if you help me. 

1) In two different kind of problem, when I used SSA or PSO algorithm, I get same values for Global and current best. is it natural? or there's a problem with my code? or the library problem? 

2) Actually I was looking at your code for sparrow search algorithm, and it sound that there are some difference in your code with real formula in the paper
![image](https://user-images.githubusercontent.com/96341972/152229868-240c6316-3740-437e-9fa5-ede97cdb8679.png)
![image](https://user-images.githubusercontent.com/96341972/152229943-6cfda847-7766-42c8-a301-7f897da08b8a.png)
![image](https://user-images.githubusercontent.com/96341972/152230267-91dbdc41-f193-4b13-bcc2-4ab2923d1eae.png)

Best regards.
Jacob.

**Comment by thieu1995** [comment]
@jacobkndy ,

I copied the answer I sent to you via email.

I was offline by Lunar New Year and covid. There is no problem with Mealpy. 
If you look at the results, they are actually different, but very small (insufficient). I guess your problem is too hard for PSO or SSA to deal with.
Or maybe, the number of dimensions are too big. You should know, meta-heuristic algorithms in general can solve a problem with dimensions around 2-100.
1) To know which algorithm is good or not good. You can try multiple one and compare the results. You can see which one is working or not.
2) The global value and the current value may be the same in all epochs because the design of that algorithm is not good enough. That is why it gives the same value.
3) This library is implemented as in each original paper, but lots of papers are very shallow and shady. They will not tell you the whole truth behind their equations and the experiments. That is why you can see many algorithms with Base version and Original version in which I changed something in Base version to make its work. 
It is the same for the SSA, they did not describe in detail what is Q and L, how to calculate them. Based on my knowledge, it is just another way to change the direction of the new vector.
So I think using Gaussian distribution (normal distribution) here is the best option. I can easily design other complex operations, but it will change the algorithm in a different perspective.
Because when changing other's algorithms, the maximum you should do is adding a Uniform vector or Gaussian vector in the original version.
Anyway, you can try to implement the SSA by yourself with Q, L and compare the results between my version and your version.
