### ISSUE TITLE
help in search particles history 

### ISSUE THREAD

**Issue by MohammedQaraad** [thieu1995/mealpy#48]
![Untitled](https://user-images.githubusercontent.com/50431486/156901474-22c66f0e-1271-4520-9416-3b6228e7658d.png)
hi thieu 
I hope this message finds you well
it's a big favor for me to help to do figure like this 
thanks, advance

**Comment by thieu1995** [comment]
Hi @MohammedQaraad 
I can't help you with that because it is depended on your fitness function to draw this kind of figure. 

After training the model, you have the history object.
Read it here:
https://mealpy.readthedocs.io/en/latest/pages/models/mealpy.utils.html#module-mealpy.utils.history

+ To access all of the solutions: model.history.list_population  
+ To access the global best solutions after all generations: model.history.list_global_best 

+ The format of: 
	+ list_population = [population_at_epoch0, population_at_epoch1, ...., population_at_max_epoch]
	+ population = [agent0, agent1, ..., agentN]
	+ agent = [ position, target]
	+ target = [fitness, objective_list]	
	+ objective_list = [obj1, obj2, ...] 
	+ list_global_best = [global_best_at_epoch0, ..., global_best_at_max_epoch]
	+ global_best = agent = [position, target]

https://mealpy.readthedocs.io/en/latest/pages/models/mealpy.html#module-mealpy.optimizer


So based on all information above, you can draw your own fitness function with position of agents.
