### ISSUE TITLE
operands could not be broadcast together

### ISSUE THREAD

**Issue by alirezaghader** [thieu1995/mealpy#8]
I get this error when running the original sparrow search algorithm:

x_new = g_best + matmul(abs(pop[i][self.ID_POS] - g_best), A1)
ValueError: operands could not be broadcast together with shapes (18,) (2,)

**Comment by alirezaghader** [comment]
I also face this error when I run your modified version of sparrow:
x_p = deepcopy(sorted(pop[:n1], key=lambda item: item[self.ID_FIT])[0][self.ID_POS])
IndexError: list index out of range

**Comment by thieu1995** [comment]
Hi @alirezaghader ,
What version of mealpy you are using currently?
Please update the latest version by using: pip install --upgrade mealpy.
Also when you using any of algorithm in this library. Check the examples how to call and use it first.

**Comment by alirezaghader** [comment]
Hi @thieu1995,  Thanks for your reply and also for this amazing library. 
I have version 1.0.4 of the mealpy
I also use the class directly and the same errors occur.
I am sure I followed the examples correctly and some other algorithms worked fine. But I still get the error for Sparrow Algorithm

**Comment by thieu1995** [comment]
Hi @alirezaghader,

Could you try with larger pop_size such as 10, 20.
Some algorithms may have some operators which restricted with the population size.

**Comment by alirezaghader** [comment]
@thieu1995 , 
Unfortunately, It did not work :(. I used both values (10 and 20). 
I am optimizing a deep learning model hyperparameters defined in tf.keras

**Comment by thieu1995** [comment]
@alirezaghader ,

Ofcourse they are not matching because I always save g_best in terms of solution. Meaning it is a list containing position and fitness value. So to fix this, you change it to:

x_new = g_best[self.ID_POS] + matmul(abs(pop[i][self.ID_POS] - g_best[self.ID_POS)), A1)

Ah, I check the code again. I remember it now. Since the OriginalSpaSA not good so I didn't use it anymore. But when I changed the base code. I din't update it so, that's why it pop up the error. Please use my version which is BaseSpaSA.
Or you can fix it by above code.

**Comment by alirezaghader** [comment]
@thieu1995 Oh Awesome Thank you. Now it works. I use the class directly.
