### ISSUE TITLE
[BUG]: Possible mistake in ArchOA algorithm

### ISSUE THREAD

**Issue by martines3000** [thieu1995/mealpy#87]
### Description of the bug

Comparing the implementation with the original [paper](https://link.springer.com/article/10.1007/s10489-020-01893-z) and original implementation in [Matlab](https://www.mathworks.com/matlabcentral/fileexchange/79822-archimedes-optimization-algorithm), the code has some differences.

First difference (probably the most important):
- [this line](https://github.com/thieu1995/mealpy/blob/7d9ffd7a842a527578f101575b612b433788f690/mealpy/physics_based/ArchOA.py#L140)  should be:

```py
self.pop[i][self.ID_ACC] = self.acc_max * (list_acc[i] - min_acc) / (max_acc - min_acc) + self.acc_min
```

Other notable mentions:
- [line 130](https://github.com/thieu1995/mealpy/blob/7d9ffd7a842a527578f101575b612b433788f690/mealpy/physics_based/ArchOA.py#L130) and [line 132](https://github.com/thieu1995/mealpy/blob/7d9ffd7a842a527578f101575b612b433788f690/mealpy/physics_based/ArchOA.py#L132) - Original implementation in Matlab multiplies the divisor `new_den*new_vol` with `np.random.uniform()`
- [line 124](https://github.com/thieu1995/mealpy/blob/7d9ffd7a842a527578f101575b612b433788f690/mealpy/physics_based/ArchOA.py#L124) and [line 125](https://github.com/thieu1995/mealpy/blob/7d9ffd7a842a527578f101575b612b433788f690/mealpy/physics_based/ArchOA.py#L125) - Original implementation uses the same random number in both lines

### Steps To Reproduce

Possible mistake in ArchOA implementation

**Comment by thieu1995** [comment]
@martines3000 ,

Thanks for pointing out the mistakes.

+ It is true that the first one it should be like you stated above. I forgot to use list_acc list. 
+ The 2nd, however, in the paper, the authors did not multiply it with random number.
+ The 3rd, also in the paper, they used the word "rand" everywhere. I think because they implement by Matlab. And in Matlab, when you type rand, it will generate a new number every times. So I believe it should be different random number.
If you look at Eq.4, Eq.7, Eq. 13, and Eq.14. They should be denoted them as rand_i. 

Of course, they will change something in the Matlab code to make their proposed algorithm works well because they know their proposed algorithm in the original paper will not. But If they change the equations in the paper to the Matlab code, they don't know how to explain why it has to be like that. 
For example, the original paper said TF <= 0.5 to balance the exploration and exploitation phase. However, if you look at the Matlab code, they use TF < 0.4 or TF < 0.45.

So I only implemented the algorithm based on their paper. Whether it works or not depends on its design.

**Comment by martines3000** [comment]
I appreciate your thorough explanation and also agree with all the points mentioned.
Thank you!

**Comment by martines3000** [comment]
@thieu1995 If you are interested, I added a PR where I fix the 1 line we both agree that is a bug. I left everything else unchanged :smiley:
